version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: arjunpatel89806/movie-recsys-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./processed_data:/app/processed_data
    networks:
      - recsys-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: arjunpatel89806/movie-recsys-frontend:latest
    ports:
      - "8501:8501"
    environment:
      # This tells the frontend to talk to the backend container, not localhost
      - API_URL=http://backend:8000/recommend
    depends_on:
      - backend
    networks:
      - recsys-net

networks:
  recsys-net:
    driver: bridge